import { config } from 'dotenv';
import jwt from 'jsonwebtoken';

config();


function authenticateToken(req, res, next) {
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1];
    // console.log(token);
    if (token == null) {
        return res.sendStatus(401);
    }
    else {
        jwt.verify(token, process.env.ACCESS_TOKEN, (err, response) => {
            if (err) {
                return res.sendStatus(403);
            }
            else {
                res.locals = response;
                // console.log(res.locals);
                next();
            }
        });
    }
}

// For token authorization you have to write 
// Bearer and token which generated by login

// else in authorization tab in postman you have to paste token and select bearer token

export default authenticateToken;